-- Database: Proyecto_Gimnasio_Ortiz_Oto

-- DROP DATABASE IF EXISTS "Proyecto_Gimnasio_Ortiz_Oto";

CREATE DATABASE "Gimnasio_Ortiz_Oto"
    WITH
    OWNER = postgres
    ENCODING = 'UTF8'
    LC_COLLATE = 'Spanish_Ecuador.1252'
    LC_CTYPE = 'Spanish_Ecuador.1252'
    LOCALE_PROVIDER = 'libc'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1

    IS_TEMPLATE = False;
/*TABLAS*/

-- 1. TABLA CLIENTE
CREATE TABLE cliente (
    id_cliente INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(120) NOT NULL,
    cedula VARCHAR(20) NOT NULL UNIQUE,
    telefono VARCHAR(20),
    email VARCHAR(150) UNIQUE,
    fecha_registro DATE DEFAULT CURRENT_DATE
);

-- 2. TABLA MEMBRESÍA
CREATE TABLE membresia (
    id_membresia INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(80) NOT NULL,
    duracion_meses INT NOT NULL CHECK (duracion_meses > 0),
    precio DECIMAL(10,2) NOT NULL CHECK (precio >= 0),
    descripcion VARCHAR(500)
);

-- 3. TABLA INSCRIPCIÓN MEMBRESÍA
CREATE TABLE inscripcion_membresia (
    id_inscripcionM INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cliente INT NOT NULL,
    id_membresia INT NOT NULL,
    fecha_inicio DATE DEFAULT CURRENT_DATE,
    fecha_fin DATE,
    estado VARCHAR(20) DEFAULT 'Activa' CHECK (estado IN ('Activa', 'Expirada', 'Cancelada')),
    FOREIGN KEY (id_cliente) REFERENCES cliente(id_cliente),
    FOREIGN KEY (id_membresia) REFERENCES membresia(id_membresia)
);

-- 4. TABLA ENTRENADOR
CREATE TABLE entrenador (
    id_entrenador INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(120) NOT NULL,
    especialidad VARCHAR(50) CHECK (especialidad IN (
        'Fuerza y Acondicionamiento',
        'Pérdida de Peso',
        'Hipertrofia Muscular',
        'Rehabilitación y Prevención',
        'Salud y Bienestar General'
    )),
    telefono VARCHAR(20)
);

-- 5. TABLA RUTINA
CREATE TABLE rutina (
    id_rutina INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(120) NOT NULL,
    nivel VARCHAR(20) DEFAULT 'Principiante' CHECK (nivel IN ('Principiante', 'Intermedio', 'Avanzado')),
    objetivo VARCHAR(200),
    id_cliente INT NOT NULL,
    id_entrenador INT,
    FOREIGN KEY (id_cliente) REFERENCES cliente(id_cliente),
    FOREIGN KEY (id_entrenador) REFERENCES entrenador(id_entrenador)
);

-- 6. TABLA EJERCICIO
CREATE TABLE ejercicio (
    id_ejercicio INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(120) NOT NULL,
    grupo_muscular VARCHAR(50) CHECK (grupo_muscular IN (
        'Pecho', 'Espalda', 'Hombros', 'Piernas', 
        'Brazos', 'Abdomen', 'Cardio', 'Full Body'
    )),
    descripcion VARCHAR(500)
);

-- 7. TABLA RUTINA_EJERCICIO
CREATE TABLE rutina_ejercicio (
    id_rutina_ejercicio INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_rutina INT NOT NULL,
    id_ejercicio INT NOT NULL,
    series INT CHECK (series > 0),
    repeticiones VARCHAR(20),
    descanso INT CHECK (descanso >= 0),
    FOREIGN KEY (id_rutina) REFERENCES rutina(id_rutina) ON DELETE CASCADE,
    FOREIGN KEY (id_ejercicio) REFERENCES ejercicio(id_ejercicio)
);

-- 8. TABLA NUTRICIONISTA
CREATE TABLE nutricionista (
    id_nutricionista INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(120) NOT NULL,
    especialidad VARCHAR(50) CHECK (especialidad IN (
        'Fuerza y Acondicionamiento',
        'Pérdida de Peso',
        'Hipertrofia Muscular',
        'Rehabilitación y Prevención',
        'Salud y Bienestar General',
        'Especialista en nutrición deportiva y clínica'	
    )),
    telefono VARCHAR(20)
);

-- 9. TABLA EVALUACIÓN NUTRICIONAL
CREATE TABLE evaluacion_nutricional (
    id_evaluacion INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cliente INT NOT NULL,
    id_nutricionista INT,
    peso DECIMAL(5,2) CHECK (peso > 0 AND peso < 300),
    altura DECIMAL(4,2) CHECK (altura > 0.5 AND altura < 2.5),
    imc DECIMAL(5,2),
    objetivo VARCHAR(200),
    recomendaciones VARCHAR(1000),
    fecha DATE DEFAULT CURRENT_DATE,
    FOREIGN KEY (id_cliente) REFERENCES cliente(id_cliente),
    FOREIGN KEY (id_nutricionista) REFERENCES nutricionista(id_nutricionista)
);

-- 10. TABLA DIETA
CREATE TABLE dieta (
    id_dieta INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_evaluacion INT NOT NULL,
    descripcion VARCHAR(1000),
    calorias_diarias INT CHECK (calorias_diarias > 0),
    FOREIGN KEY (id_evaluacion) REFERENCES evaluacion_nutricional(id_evaluacion)
);

-- 11. TABLA FACTURA
CREATE TABLE factura (
    id_factura INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cliente INT NOT NULL,
    fecha TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    total DECIMAL(12,2) CHECK (total >= 0),
    FOREIGN KEY (id_cliente) REFERENCES cliente(id_cliente)
);

-- 12. TABLA PAGO
CREATE TABLE pago (
    id_pago INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_factura INT NOT NULL,
    fecha_pago TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    monto DECIMAL(12,2) CHECK (monto > 0),
    metodo_pago VARCHAR(30) DEFAULT 'Efectivo' CHECK (metodo_pago IN (
        'Efectivo',
        'Tarjeta Débito',
        'Tarjeta Crédito',
        'Transferencia Bancaria',
        'Débito Automático'
    )),
    FOREIGN KEY (id_factura) REFERENCES factura(id_factura)
);

--13.TABLA PARA HACER LOGIN
CREATE TABLE cliente_auth (
    id_auth INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cliente INT NOT NULL UNIQUE,
    email VARCHAR(150) NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    estado VARCHAR(20) DEFAULT 'Activo' CHECK (estado IN ('Activo', 'Bloqueado')),
    fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (id_cliente) REFERENCES cliente(id_cliente) ON DELETE CASCADE
);

/*REGISTROS MIOS Y DE GELEN*/
INSERT INTO cliente (nombre, cedula, telefono, email, fecha_registro) VALUES
('Camilo Rodriguez', '1754678976', '0989564352', 'camiRodriguez@gmail.com', '2025-08-15'),
('Emilia González', '1765435632', '0987654321', 'emiliaGonzalez@gmail.com', '2025-08-20'),
('Carlos Ruiz', '1789095643', '0976543210', 'carlosRuiz@gmail.com', '2025-08-23'),
('Ana Silva', '1756432318', '0965490109', 'anaSilva@gmail.com', '2025-08-25'),
('Luis Castro', '1789564356', '0967321997', 'luisCastro@gmail.com', '2025-08-25'),
('Patricia Torres', '1756895432', '0943289980', 'patriciaTorres@gmail.com', '2025-09-15'),
('Eliana Flores', '1767546832', '0965109876', 'elianaFlores@gmail.com', '2025-09-22'),
('Laura Vega', '1789075643', '0921228765', 'lauraVega@gmail.com', '2025-10-06'),
('Diego Vargas', '1789765432', '0967047654', 'diegoVargas@gmail.com', '2025-10-14'),
('Sofía Méndez', '1789075647', '0977876543', 'sofiaMendez@gmail.com', '2025-10-24'),
('Fernando Reyes', '1789364251', '0908760532', 'fernandoReyes@gmail.com', '2025-10-25'),
('Valentina Sánchez', '1789564321', '0907654321', 'valentinaSanchez@gmail.com', '2025-11-08'),
('Miguel Ramos', '1789564352', '0996543210', 'miguelRamos@gmail.com', '2025-11-10'),
('Enrique Guerrero', '1767548943', '0935432169', 'enriqueGuerrero@gmail.com', '2025-11-15');

select * from cliente;
INSERT INTO membresia (nombre, duracion_meses, precio, descripcion) VALUES
('Básica', 1, 35.00, 'Acceso a todas las áreas del gimnasio en horario normal sin entrenador'),
('Estándar', 3, 90.00, 'Acceso completo al gimnasio + 2 clases de spinning o yoga por semana + descuento en productos del gym.'),
('Premium', 6, 165.00, 'Acceso total + clases grupales ilimitadas (spinning, yoga, zumba, boxeo) + 1 sesión mensual con entrenador personal.'),
('VIP', 12, 300.00, 'Acceso total VIP + entrenador personal diario + plan nutricional personalizado + clases grupales ilimitadas + toalla y bebida incluidas'),
('Estudiante', 1, 25.00, 'Membresía especial para estudiantes con carnet vigente'),
('Pareja', 3, 150.00, 'Membresía compartida para 2 personas + 4 clases grupales combinadas al mes.');

INSERT INTO inscripcion_membresia (id_cliente, id_membresia, fecha_inicio, fecha_fin, estado) VALUES
(1, 4, '2025-08-15', '2026-08-15', 'Activa'),
(2, 3, '2025-08-20', '2026-02-20', 'Activa'),
(3, 2, '2025-08-23', '2025-11-23', 'Activa'),
(4, 3, '2025-08-25', '2026-02-25', 'Activa'),
(5, 1, '2025-08-25', '2025-09-25', 'Expirada'),
(6, 4, '2025-09-15', '2026-09-15', 'Activa'),
(7, 2, '2025-09-22', '2025-12-22', 'Activa'),
(8, 3, '2025-10-06', '2026-04-06', 'Activa'),
(9, 1, '2025-10-14', '2025-11-14', 'Expirada'),
(10, 4, '2025-10-24', '2026-10-24', 'Activa'),
(11, 2, '2025-10-25', '2026-01-25', 'Activa'),
(12, 1, '2025-11-08', '2025-12-08', 'Activa'),
(13, 5, '2025-11-10', '2025-12-10', 'Activa'),
(14, 3, '2025-11-15', '2026-05-15', 'Activa'),
(3, 4, '2025-12-23', '2026-12-23', 'Activa'),
(5, 6, '2025-10-01', '2026-01-01', 'Activa');

INSERT INTO entrenador (nombre, especialidad, telefono) VALUES
('Andres Oto', 'Fuerza y Acondicionamiento', '0967234577'),
('Gelen Ortiz', 'Pérdida de Peso', '0992345678'),
('Dennise Pazmiño', 'Hipertrofia Muscular', '0993146759'),
('Max Rojas', 'Rehabilitación y Prevención', '0912581290');

INSERT INTO rutina (nombre, nivel, objetivo, id_cliente, id_entrenador) VALUES
('Rutina de Fuerza Total', 'Avanzado', 'Aumentar fuerza máxima de grupos musculares', 1, 1),
('Plan de Pérdida de Grasa', 'Intermedio', 'Reducir porcentaje de grasa corporal', 2, 2),
('Hipertrofia 4 Días', 'Intermedio', 'Ganancia de masa muscular', 3, 3),
('Rehabilitación Rodilla', 'Principiante', 'Fortalecer rodilla tras lesión', 4, 4),
('Bienestar General', 'Principiante', 'Mejorar condición física general', 5, 1),
('Full Body', 'Principiante', 'Adaptación al ejercicio', 6, 1),
('Push Pull Legs', 'Avanzado', 'Hipertrofia muscular avanzada', 10, 3),
('Cardio y Tonificación', 'Intermedio', 'Resistencia cardiovascular y tono muscular', 8, 2),
('Fuerza Funcional', 'Intermedio', 'Mejorar movimientos cotidianos', 11, 1),
('Definición Muscular', 'Avanzado', 'Marcar y definir musculatura', 1, 3);

-- Insertar ejercicios con grupos musculares
INSERT INTO ejercicio (nombre, grupo_muscular, descripcion) VALUES
-- PECHO
('Press de banca con barra', 'Pecho', 'Ejercicio básico para desarrollo de pectorales'),
('Press de banca con mancuernas', 'Pecho', 'Permite mayor rango de movimiento que con barra'),
('Aperturas con mancuernas', 'Pecho', 'Aislamiento de pectorales para definición'),
('Flexiones', 'Pecho', 'Ejercicio con peso corporal para pecho y tríceps'),
('Press inclinado', 'Pecho', 'Enfocado en porción superior del pectoral'),
-- ESPALDA
('Dominadas', 'Espalda', 'Ejercicio fundamental para espalda ancha'),
('Remo con barra', 'Espalda', 'Para desarrollo de espesor en espalda'),
('Peso muerto', 'Espalda', 'Ejercicio compuesto para espalda baja y piernas'),
('Jalón al pecho', 'Espalda', 'Para amplitud de espalda en máquina'),
('Remo con mancuerna', 'Espalda', 'Ejercicio unilateral para equilibrio muscular'),
-- HOMBROS
('Press militar', 'Hombros', 'Ejercicio básico para desarrollo de hombros'),
('Elevaciones laterales', 'Hombros', 'Para desarrollo de deltoides laterales'),
('Face Pull', 'Hombros', 'Para salud articular y rotadores externos'),
('Press Arnold', 'Hombros', 'Variación con rotación para mayor activación'),
('Encogimientos de hombros', 'Hombros', 'Para desarrollo de trapecio superior'),
-- PIERNAS
('Sentadillas', 'Piernas', 'Ejercicio fundamental para desarrollo de piernas'),
('Prensa de piernas', 'Piernas', 'Para fuerza en piernas con soporte de espalda'),
('Extensiones de cuádriceps', 'Piernas', 'Aislamiento para parte frontal del muslo'),
('Curl femoral', 'Piernas', 'Para isquiotibiales (parte posterior del muslo)'),
('Peso muerto rumano', 'Piernas', 'Para femoral, glúteos y espalda baja'),
-- BRAZOS
('Curl de bíceps con barra', 'Brazos', 'Ejercicio básico para desarrollo de bíceps'),
('Fondos en paralelas', 'Brazos', 'Para tríceps y porción inferior del pecho'),
('Extensión de tríceps en polea', 'Brazos', 'Aislamiento para tríceps con tensión constante'),
('Curl martillo', 'Brazos', 'Para braquial y antebrazo, con agarre neutral'),
('Press francés', 'Brazos', 'Para cabeza larga del tríceps'),
-- ABDOMEN
('Crunch', 'Abdomen', 'Para recto abdominal (six-pack)'),
('Plancha', 'Abdomen', 'Para core completo y estabilidad'),
('Elevaciones de piernas', 'Abdomen', 'Para abdominales inferiores'),
('Russian Twist', 'Abdomen', 'Para oblicuos y rotación del core'),
-- CARDIO
('Correr en cinta', 'Cardio', 'Cardiovascular de impacto para resistencia'),
('Bicicleta estática', 'Cardio', 'Cardio de bajo impacto para piernas'),
('Elíptica', 'Cardio', 'Cardio completo de bajo impacto'),
-- FULL BODY
('Burpees', 'Full Body', 'Ejercicio completo de fuerza y cardio'),
('Clean and Press', 'Full Body', 'Ejercicio olímpico completo'),
('Thruster', 'Full Body', 'Combinación de sentadilla y press');


INSERT INTO rutina_ejercicio (id_rutina, id_ejercicio, series, repeticiones, descanso) VALUES
-- Rutina 1: Fuerza Total (Avanzado)
(1, 1, 5, '5', 180),      
(1, 16, 5, '5', 180),     
(1, 8, 4, '6', 180),      
(1, 11, 4, '6', 120),     

-- Rutina 2: Pérdida de Grasa (Intermedio)
(2, 33, 4, '15', 30),     
(2, 30, 1, '20 min', 0),  
(2, 26, 3, '60 seg', 30), 
(2, 31, 1, '15 min', 0),  

-- Rutina 3: Hipertrofia 4 Días (Intermedio)
(3, 1, 4, '8-10', 90),    
(3, 5, 3, '10-12', 90),   
(3, 16, 4, '10-12', 90),  
(3, 18, 4, '12-15', 60),  

-- Rutina 4: Rehabilitación Rodilla (Principiante)
(4, 17, 3, '10', 60),     
(4, 31, 1, '15 min', 0),  
(4, 26, 2, '30 seg', 30), 

-- Rutina 5: Bienestar general del cuerpo (Principiante)
(5, 16, 3, '12', 60),     
(5, 6, 3, '8-10', 90),    
(5, 26, 3, '30 seg', 30), 
(5, 30, 1, '15 min', 0),  

-- Rutina 6: Full Body (Principiante)
(6, 16, 3, '10', 90),    
(6, 1, 3, '10', 90),      
(6, 7, 3, '10', 90),     
(6, 25, 3, '15', 60),     

-- Rutina 7: Push Pull Legs (Avanzado)
(7, 1, 4, '6-8', 120),    
(7, 5, 4, '8-10', 90),   
(7, 11, 4, '8-10', 90),   
(7, 6, 4, '6-8', 120),    
(7, 16, 5, '8-10', 120),  

-- Rutina 8: Cardio y Tonificación (Intermedio)
(8, 30, 1, '25 min', 0),  
(8, 33, 3, '12', 45),     
(8, 32, 1, '15 min', 0),  
(8, 29, 3, '20', 45),     

-- Rutina 9: Fuerza Funcional (Intermedio)
(9, 8, 4, '5', 150),      
(9, 16, 4, '8', 120),     
(9, 33, 3, '10', 60),     
(9, 35, 3, '8', 120),     

-- Rutina 10: Definición Muscular (Avanzado)
(10, 1, 4, '12-15', 60), 
(10, 5, 4, '12-15', 60),  
(10, 12, 3, '15', 45),    
(10, 21, 3, '15', 45);    


INSERT INTO nutricionista (nombre, especialidad, telefono) VALUES
('Dr. Lucia Martinez', 'Especialista en nutrición deportiva y clínica', '0987674321'),
('Dra. Ricardo Herrera', 'Especialista en nutrición deportiva y clínica', '0914103890');

select*from evaluacion_nutricional;

INSERT INTO evaluacion_nutricional (id_cliente, id_nutricionista, peso, altura, imc, objetivo, recomendaciones, fecha) VALUES
(1, 2, 85.5, 1.78, 27.0, 'Ganancia de masa muscular', 'Aumentar ingesta calórica en 500 kcal. Proteína: 2g/kg. Entrenar 4-5 veces/semana.', '2025-08-20'),
(2, 1, 72.3, 1.65, 26.6, 'Pérdida de grasa', 'Déficit calórico de 300 kcal. Cardio 3 veces/semana. Hidratación constante.', '2025-08-25'),
(3, 2, 68.0, 1.72, 23.0, 'Aumento de masa muscular', 'Superávit de 400 kcal. Proteína alta. Descanso adecuado.', '2025-08-28'),
(4, 1, 58.5, 1.60, 22.9, 'Mantener peso saludable', 'Dieta balanceada. Ejercicio regular 3-4 veces/semana.', '2025-09-01'),
(5, 1, 90.2, 1.75, 29.4, 'Reducción de peso', 'Déficit de 500 kcal. Eliminar azúcares añadidos. Caminar 30 min diarios.', '2025-09-05'),
(6, 2, 75.0, 1.70, 26.0, 'Ganancia muscular', 'Dieta hipercalórica. Proteína 2.2g/kg. Carbohidratos complejos.', '2025-09-20'),
(8, 1, 63.0, 1.68, 22.3, 'Tonificación', 'Dieta normocalórica. Balance de macros. Ejercicio mixto.', '2025-10-10'),
(10, 2, 78.5, 1.76, 25.3, 'Hipertrofia', 'Superávit moderado. Timing de nutrientes. Suplementación básica.', '2025-10-28'),
(11, 1, 88.0, 1.73, 29.4, 'Pérdida de grasa', 'Déficit calórico gradual. Aumentar actividad física. Controlar porciones.', '2025-11-01'),
(1, 2, 87.0, 1.78, 27.5, 'Mantenimiento y definición', 'Mantener superávit leve. Ajustar macros según progreso.', '2025-09-15');

INSERT INTO dieta (id_evaluacion, descripcion, calorias_diarias) VALUES
(1, 'Desayuno: Avena con frutas y proteína. Almuerzo: Pollo con arroz y vegetales. Cena: Pescado con ensalada. Snacks: Frutos secos y batido proteico.', 3200),
(2, 'Desayuno: Huevos con espinaca. Almuerzo: Ensalada con atún. Cena: Pechuga a la plancha con brócoli. Snacks: Yogurt griego.', 1800),
(3, 'Desayuno: Batido proteico con avena. Almuerzo: Carne magra con quinoa. Cena: Salmón con vegetales. Snacks: Frutas y almendras.', 2800),
(4, 'Desayuno: Tostadas integrales con aguacate. Almuerzo: Pasta integral con vegetales. Cena: Pollo al horno. Snacks: Frutas frescas.', 2000),
(5, 'Desayuno: Claras de huevo con vegetales. Almuerzo: Ensalada completa con proteína. Cena: Pescado al vapor con espárragos. Snacks: Vegetales crudos.', 1600),
(6, 'Desayuno: Pancakes proteicos. Almuerzo: Arroz con carne y vegetales. Cena: Pasta con atún. Snacks: Batido de proteína y banana.', 3000),
(7, 'Desayuno: Yogurt con granola. Almuerzo: Pollo con batata. Cena: Ensalada de quinoa. Snacks: Frutas y nueces.', 2200),
(8, 'Desayuno: Avena proteica. Almuerzo: Res con arroz integral. Cena: Pavo con vegetales. Snacks: Batidos y frutos secos.', 2900),
(9, 'Desayuno: Huevos revueltos light. Almuerzo: Pescado con ensalada. Cena: Pollo con verduras al vapor. Snacks: Gelatina y té verde.', 1700),
(10, 'Desayuno: Batido verde con proteína. Almuerzo: Pechuga con arroz integral. Cena: Atún con quinoa. Snacks: Frutas y proteína.', 2600);
select*from factura;

INSERT INTO factura (id_cliente, fecha, total) VALUES
(1, '2025-08-15 10:30:00', 300.00),
(2, '2025-08-20 14:15:00', 165.00),
(3, '2025-08-23 09:45:00', 90.00),
(4, '2025-08-25 16:20:00', 165.00),
(5, '2025-08-25 11:00:00', 35.00),
(6, '2025-09-15 13:30:00', 300.00),
(7, '2025-09-22 10:00:00', 90.00),
(8, '2025-10-06 15:45:00', 165.00),
(9, '2025-10-14 12:15:00', 35.00),
(10, '2025-10-24 09:30:00', 300.00),
(11, '2025-10-25 14:00:00', 90.00),
(12, '2025-11-08 11:30:00', 35.00),
(13, '2025-11-10 10:15:00', 25.00),
(14, '2025-11-15 16:45:00', 165.00),
(3, '2025-12-23 10:00:00', 300.00),
(5, '2025-10-01 15:30:00', 150.00),
(1, '2025-09-15 12:00:00', 50.00);

INSERT INTO pago (id_factura, fecha_pago, monto, metodo_pago) VALUES
(1, '2025-08-15 10:35:00', 300.00, 'Tarjeta Crédito'),
(2, '2025-08-20 14:20:00', 165.00, 'Transferencia Bancaria'),
(3, '2025-08-23 09:50:00', 90.00, 'Efectivo'),
(4, '2025-08-25 16:25:00', 165.00, 'Tarjeta Débito'),
(5, '2025-08-25 11:05:00', 35.00, 'Efectivo'),
(6, '2025-09-15 13:35:00', 150.00, 'Tarjeta Crédito'),
(6, '2025-10-15 10:00:00', 150.00, 'Transferencia Bancaria'),
(7, '2025-09-22 10:05:00', 90.00, 'Efectivo'),
(8, '2025-10-06 15:50:00', 165.00, 'Débito Automático'),
(9, '2025-10-14 12:20:00', 35.00, 'Efectivo'),
(10, '2025-10-24 09:35:00', 300.00, 'Tarjeta Crédito'),
(11, '2025-10-25 14:05:00', 90.00, 'Transferencia Bancaria'),
(12, '2025-11-08 11:35:00', 35.00, 'Efectivo'),
(13, '2025-11-10 10:20:00', 25.00, 'Efectivo'),
(14, '2025-11-15 16:50:00', 165.00, 'Tarjeta Débito'),
(15, '2025-12-23 10:10:00', 300.00, 'Tarjeta Crédito'),
(16, '2025-10-01 15:35:00', 150.00, 'Efectivo'),
(17, '2025-09-15 12:05:00', 50.00, 'Tarjeta Débito');
/*
*/


/*PARTE GELEN*/
-- 4. Consultas y operaciones
-- Clientes con el estado de su membresía
SELECT c.nombre AS cliente,
       i.estado,
       i.fecha_inicio,
       i.fecha_fin
FROM cliente c
INNER JOIN inscripcion_membresia i
ON c.id_cliente = i.id_cliente;

-- Rutinas completas con entrenador 
SELECT c.nombre AS cliente,
       r.nombre AS rutina, 
       r.nivel, 
       r.objetivo,
       e.nombre AS entrenador
FROM cliente c
INNER JOIN rutina r ON c.id_cliente = r.id_cliente
LEFT JOIN entrenador e ON r.id_entrenador = e.id_entrenador;

-- Clientes con membresías próximas a expirar
SELECT c.nombre,
       im.fecha_fin
FROM cliente c
JOIN inscripcion_membresia im ON c.id_cliente = im.id_cliente
WHERE im.estado = 'Activa'
  AND im.fecha_fin <= CURRENT_DATE + INTERVAL '30 days'
ORDER BY im.fecha_fin;

-- Rutinas que han sido asignadas a los clientes con su respectivo entrenador
SELECT c.nombre AS cliente,
       r.nombre AS rutina,
       r.nivel,
       e.nombre AS entrenador
FROM cliente c
JOIN rutina r ON c.id_cliente = r.id_cliente
LEFT JOIN entrenador e ON r.id_entrenador = e.id_entrenador
ORDER BY e.nombre;


-- Clientes activos en el gimnasio
CREATE VIEW vista_clientes_activos AS
SELECT c.nombre,
       m.nombre AS membresia,
       im.fecha_fin
FROM cliente c
JOIN inscripcion_membresia im ON c.id_cliente = im.id_cliente
JOIN membresia m ON im.id_membresia = m.id_membresia
WHERE im.estado = 'Activa';

SELECT * FROM vista_clientes_activos;

-- Clientes que pueden ingresar desde el día de hoy 
SELECT c.nombre,
		im.fecha_fin
FROM cliente c
JOIN inscripcion_membresia im ON c.id_cliente = im.id_cliente
WHERE im.estado = 'Activa'
  AND im.fecha_fin >= CURRENT_DATE;
  
-- Estadísticas gimnasio 
SELECT 
    date_trunc('month', f.fecha) AS mes,
    COUNT(DISTINCT f.id_cliente) AS clientes_facturados,
    COUNT(f.id_factura) AS total_facturas,
    SUM(f.total) AS ingresos_totales,
    MIN(f.total) AS factura_minima,
    MAX(f.total) AS factura_maxima
FROM factura f
WHERE f.fecha >= CURRENT_DATE - INTERVAL '12 months'
GROUP BY date_trunc('month', f.fecha)
ORDER BY mes DESC;

-- Clientes con más de una factura
SELECT nombre
FROM cliente
WHERE id_cliente IN (
    SELECT id_cliente
    FROM factura
    GROUP BY id_cliente
    HAVING COUNT(*) > 1
);
-- Total pagado por cliente hasta el momento
SELECT c.nombre, 
SUM(p.monto) AS total_pagado
FROM cliente c
JOIN factura f ON c.id_cliente = f.id_cliente
JOIN pago p ON f.id_factura = p.id_factura
GROUP BY c.nombre;

-- VISTA DE CLIENTES CON RUTINA Y FECHAS DE INSCRIPCION- FINALIZACIÓN
CREATE VIEW vista_clientes_rutina AS
SELECT c.nombre AS cliente, 
		r.nombre AS rutina, 
		e.nombre AS entrenador,
		im.fecha_inicio,
		im.fecha_fin
FROM cliente c
JOIN rutina r ON c.id_cliente = r.id_cliente
LEFT JOIN entrenador e ON r.id_entrenador = e.id_entrenador
JOIN inscripcion_membresia im ON c.id_cliente = im.id_cliente;

-- Ejemplo: Actualizar el estado activo considerando la fecha actual 
UPDATE inscripcion_membresia
SET estado = CASE
  WHEN fecha_fin >= CURRENT_DATE THEN 'Activa'
  ELSE 'Expirada'
END;

-- Ejemplo: Eliminar registro si sobrepasa los 3 años de expiración de membresía
DELETE FROM inscripcion_membresia
WHERE estado = 'Expirada'
AND fecha_fin < CURRENT_DATE - INTERVAL '3 years';

-- CREACION DE FUNCIONES

-- ACTUALIZACIÓN DE ESTADO DE MEMBRESÍA
CREATE OR REPLACE FUNCTION Actualizar_estado_membresia()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.fecha_fin < CURRENT_DATE THEN
        NEW.estado := 'Expirada';
    ELSE
        NEW.estado := 'Activa';
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- EVITAR QUE LOS CLEINTES TENGAN MAS DE 3 RUTINAS ASIGNADAS 

CREATE OR REPLACE FUNCTION Limitar_rutinas_cliente()
RETURNS TRIGGER AS $$
DECLARE
    total_rutinas INT;
BEGIN
    SELECT COUNT(*) INTO total_rutinas
    FROM rutina
    WHERE id_cliente = NEW.id_cliente;

    IF total_rutinas >= 3 THEN
        RAISE EXCEPTION 'El cliente ya tiene el máximo de 3 rutinas asignadas';
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;


-- CALCULO DE INDICE DE MASA CORPORAL 
CREATE OR REPLACE FUNCTION calcular_IMC()
RETURNS TRIGGER AS $$
BEGIN
    NEW.imc := ROUND(NEW.peso / (NEW.altura * NEW.altura), 2);
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;


-- TRIGGERS

-- LLAMADA A LA FUNCION PARA ACTUALIZAR MEMBRESÍA
CREATE TRIGGER trg_actualizar_estado_membresia
BEFORE INSERT OR UPDATE ON inscripcion_membresia
FOR EACH ROW
EXECUTE FUNCTION actualizar_estado_membresia();

-- LLAMA DE LA FUNCIÓN PARA LIMITAR RUTINAS DE CLIENTES
CREATE TRIGGER trg_limite_rutinas_cliente
BEFORE INSERT ON rutina
FOR EACH ROW
EXECUTE FUNCTION limitar_rutinas_cliente();

-- LLAMADA DE LA FUNCION calcular_IMC
CREATE TRIGGER trg_calcular_IMC
BEFORE INSERT OR UPDATE ON evaluacion_nutricional
FOR EACH ROW
EXECUTE FUNCTION calcular_IMC();

-- PROCEDIMIENTO ALMACENADO

CREATE OR REPLACE PROCEDURE registrar_pago(
    p_id_factura INT,
    p_monto DECIMAL,
    p_metodo VARCHAR
)
LANGUAGE plpgsql
AS $$
BEGIN
    INSERT INTO pago (id_factura, monto, metodo_pago)
    VALUES (p_id_factura, p_monto, p_metodo);

    UPDATE factura
    SET total = total + p_monto
    WHERE id_factura = p_id_factura;
END;
$$;
/*FIN DE LA PARTE GELEN*/

-- 5. Administración y seguridad
CREATE ROLE rol_administrador;
CREATE ROLE rol_recepcionista;
CREATE ROLE rol_entrenador;
CREATE ROLE rol_nutricionista;
CREATE ROLE rol_cliente;

-- ROL ADMINISTRADOR (acceso completo)
GRANT ALL PRIVILEGES ON DATABASE "Gimnasio_Ortiz_Oto" TO rol_administrador;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO rol_administrador;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO rol_administrador;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO rol_administrador;

-- ROL RECEPCIONISTA (gestión de clientes, membresías, pagos)
GRANT SELECT, INSERT, UPDATE ON cliente TO rol_recepcionista;
GRANT SELECT ON membresia TO rol_recepcionista;
GRANT SELECT, INSERT, UPDATE ON inscripcion_membresia TO rol_recepcionista;
GRANT SELECT, INSERT ON factura TO rol_recepcionista;
GRANT SELECT, INSERT ON pago TO rol_recepcionista;
GRANT SELECT ON rutina TO rol_recepcionista;
GRANT SELECT ON entrenador TO rol_recepcionista;
GRANT SELECT ON nutricionista TO rol_recepcionista;

-- ROL ENTRENADOR (gestión de rutinas y ejercicios)
GRANT SELECT ON cliente TO rol_entrenador;
GRANT SELECT, INSERT, UPDATE, DELETE ON rutina TO rol_entrenador;
GRANT SELECT, INSERT, UPDATE, DELETE ON rutina_ejercicio TO rol_entrenador;
GRANT SELECT ON ejercicio TO rol_entrenador;
GRANT SELECT ON entrenador TO rol_entrenador;

-- ROL NUTRICIONISTA (gestión de evaluaciones y dietas)
GRANT SELECT ON cliente TO rol_nutricionista;
GRANT SELECT, INSERT, UPDATE ON evaluacion_nutricional TO rol_nutricionista;
GRANT SELECT, INSERT, UPDATE ON dieta TO rol_nutricionista;
GRANT SELECT ON nutricionista TO rol_nutricionista;

-- ROL CLIENTE (tu info)
GRANT SELECT ON cliente TO rol_cliente;
GRANT SELECT ON inscripcion_membresia TO rol_cliente;
GRANT SELECT ON rutina TO rol_cliente;
GRANT SELECT ON rutina_ejercicio TO rol_cliente;
GRANT SELECT ON ejercicio TO rol_cliente;
GRANT SELECT ON evaluacion_nutricional TO rol_cliente;
GRANT SELECT ON dieta TO rol_cliente;
GRANT SELECT ON factura TO rol_cliente;
GRANT SELECT ON pago TO rol_cliente;

/*USUARIOS*/
-- Usuarios administradores
CREATE USER admin_gimnasio WITH PASSWORD 'admin1234';
GRANT rol_administrador TO admin_gimnasio;

-- Usuarios entrenadores (Varios) 
CREATE USER entrenador_andres WITH PASSWORD 'AndresGym123';
GRANT rol_entrenador TO entrenador_andres;

CREATE USER entrenador_gelen WITH PASSWORD 'GelenFit123';
GRANT rol_entrenador TO entrenador_gelen;

CREATE USER entrenador_denisse WITH PASSWORD 'vuelveDenisse2026';
GRANT rol_entrenador TO entrenador_denisse;

CREATE USER entrenador_max WITH PASSWORD 'MaxGym333';
GRANT rol_entrenador TO entrenador_max;

-- RECPCIONISTAS
CREATE USER recepcion_danahe_dia WITH PASSWORD 'RecepcionDia123';
GRANT rol_recepcionista TO recepcion_danahe_dia;

CREATE USER recepcion_gustavo_noche WITH PASSWORD 'RecepcionNoche123';
GRANT rol_recepcionista TO recepcion_gustavo_noche;

--NUTRICIONISTA
CREATE USER nutri_lucia WITH PASSWORD 'LuciaNutri123';
GRANT rol_nutricionista TO nutri_lucia;

CREATE USER nutri_ricardo WITH PASSWORD 'RicardoSalud';
GRANT rol_nutricionista TO nutri_ricardo;

/*6. SEGURIDAD*/
-- 1. PREVENCIÓN DE INYECCIÓN SQL
-- Ponemos esta extensión para encriptación
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- Se hace una función simple para registro seguro
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- Función simple para registro seguro
CREATE FUNCTION registrar_cliente(
    nombre_cliente VARCHAR(120),
    cedula_cliente VARCHAR(20),
    telefono_cliente VARCHAR(20),
    email_cliente VARCHAR(150),
    password_cliente TEXT
) RETURNS INTEGER AS $$
DECLARE
    nuevo_id INTEGER;
BEGIN
    -- Insertar cliente (parámetros evitan inyección)
    INSERT INTO cliente (nombre, cedula, telefono, email)
    VALUES (nombre_cliente, cedula_cliente, telefono_cliente, email_cliente)
    RETURNING id_cliente INTO nuevo_id;
    
    -- Insertar credenciales con contraseña encriptada
    INSERT INTO cliente_auth (id_cliente, email, password_hash)
    VALUES (nuevo_id, email_cliente, crypt(password_cliente, gen_salt('bf')));
    
    RETURN nuevo_id;
    
EXCEPTION
    WHEN unique_violation THEN
        RAISE EXCEPTION 'El email o cédula ya están registrados';
    WHEN others THEN
        RAISE EXCEPTION 'Error en el registro: %', SQLERRM;
END;
$$ LANGUAGE plpgsql;


-- hacemos una función simple para login
CREATE OR REPLACE FUNCTION login_cliente(
    email_cliente VARCHAR(150),
    password_cliente TEXT
) RETURNS TABLE (
    id_cliente INTEGER,
    nombre VARCHAR(120),
    email VARCHAR(150),
    estado VARCHAR(20)
) AS $$
BEGIN
    RETURN QUERY
    SELECT c.id_cliente, c.nombre, c.email, ca.estado
    FROM cliente c
    INNER JOIN cliente_auth ca ON c.id_cliente = ca.id_cliente
    WHERE ca.email = email_cliente 
      AND ca.password_hash = crypt(password_cliente, ca.password_hash)
      AND ca.estado = 'Activo';
    
    IF NOT FOUND THEN
        RAISE EXCEPTION 'Credenciales incorrectas o cuenta inactiva';
    END IF;
END;
$$ LANGUAGE plpgsql;

/*PARA CIFRAR LAS CONTRASEÑAS HACEMOS TRIGGER*/
-- Trigger para encriptar automáticamente
CREATE FUNCTION encriptar_password()
RETURNS TRIGGER AS $$
BEGIN
    -- Solo si es nuevo registro o cambió la contraseña
    IF TG_OP = 'INSERT' OR NEW.password_hash <> OLD.password_hash THEN
        NEW.password_hash := crypt(NEW.password_hash, gen_salt('bf'));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Aplicar trigger a cliente_auth
CREATE TRIGGER trig_encriptar_password
BEFORE INSERT OR UPDATE ON cliente_auth
FOR EACH ROW
EXECUTE FUNCTION encriptar_password();

-- Función para cambiar contraseña
CREATE FUNCTION cambiar_password(
    id_cliente_param INTEGER,
    password_actual TEXT,
    password_nuevo TEXT
) RETURNS BOOLEAN AS $$
DECLARE
    hash_actual TEXT;
BEGIN
    -- Obtener hash actual
    SELECT password_hash INTO hash_actual
    FROM cliente_auth
    WHERE id_cliente = id_cliente_param;
    
    -- Verificar contraseña actual
    IF hash_actual = crypt(password_actual, hash_actual) THEN
        -- Actualizar con nueva contraseña (el trigger la encriptará)
        UPDATE cliente_auth 
        SET password_hash = password_nuevo
        WHERE id_cliente = id_cliente_param;
        
        RETURN TRUE;
    ELSE
        RETURN FALSE;
    END IF;
END;
$$ LANGUAGE plpgsql;

-- 3. CONTROL DE ACCESOS 

--Asegurar que las funciones estén disponibles para el rol
GRANT EXECUTE ON FUNCTION registrar_cliente TO rol_administrador;
GRANT EXECUTE ON FUNCTION login_cliente TO rol_administrador;
GRANT EXECUTE ON FUNCTION cambiar_password TO rol_administrador;
GRANT EXECUTE ON FUNCTION encriptar_password TO rol_administrador;

-- Vista opcional para datos seguros
CREATE OR REPLACE VIEW vista_datos_seguros AS
SELECT 
    c.id_cliente,
    c.nombre,
    SUBSTRING(c.cedula FROM 1 FOR 3) || '****' || SUBSTRING(c.cedula FROM 8 FOR 3) as cedula_mask,
    CASE 
        WHEN LENGTH(c.telefono) >= 9 THEN 
            SUBSTRING(c.telefono FROM 1 FOR 3) || '****' || SUBSTRING(c.telefono FROM LENGTH(c.telefono)-2 FOR 3)
        ELSE c.telefono
    END as telefono_mask,
    c.email,
    c.fecha_registro,
    ca.estado as estado_cuenta,
    ca.fecha_creacion as fecha_registro_portal
FROM cliente c
LEFT JOIN cliente_auth ca ON c.id_cliente = ca.id_cliente;

GRANT SELECT ON vista_datos_seguros TO rol_administrador;
GRANT SELECT ON vista_datos_seguros TO rol_recepcionista;
GRANT SELECT ON vista_datos_seguros TO rol_entrenador;
GRANT SELECT ON vista_datos_seguros TO rol_nutricionista;


-- Para el rol_cliente, una vista más restringida
CREATE OR REPLACE VIEW vista_datos_cliente AS
SELECT 
    c.id_cliente,
    c.nombre,
    c.telefono,
    c.email,
    c.fecha_registro
FROM cliente c;

GRANT SELECT ON vista_datos_cliente TO rol_cliente;
/*
*/


/*8.Rendimiento*/
--1. CONSULTAS OPTIMIZADAS
-- . Dashboard Clientes (Combina 3 consultas originales)
EXPLAIN
SELECT 
    c.nombre,
    im.estado AS estado_membresia,
    im.fecha_inicio,
    im.fecha_fin,
    r.nombre AS rutina,
    e.nombre AS entrenador,
    CASE 
        WHEN im.fecha_fin BETWEEN CURRENT_DATE AND CURRENT_DATE + INTERVAL '30 days' 
        THEN 'Por expirar'
        ELSE 'Vigente'
    END AS alerta_vencimiento
FROM cliente c
INNER JOIN inscripcion_membresia im ON c.id_cliente = im.id_cliente
LEFT JOIN rutina r ON c.id_cliente = r.id_cliente
LEFT JOIN entrenador e ON r.id_entrenador = e.id_entrenador
WHERE im.estado = 'Activa'
  AND im.fecha_fin >= CURRENT_DATE
ORDER BY im.fecha_fin, c.nombre;

-- 2. Estadísticas Consolidadas (Combina estadísticas + pagos)
SELECT 
    DATE_TRUNC('month', f.fecha) AS mes,
    COUNT(DISTINCT f.id_cliente) AS clientes_activos,
    COUNT(DISTINCT CASE WHEN p.monto > 0 THEN f.id_cliente END) AS clientes_pagaron,
    SUM(p.monto) AS ingresos_totales,
    AVG(p.monto) AS promedio_pago
FROM factura f
LEFT JOIN pago p ON f.id_factura = p.id_factura
WHERE f.fecha >= CURRENT_DATE - INTERVAL '6 months'
GROUP BY DATE_TRUNC('month', f.fecha)
ORDER BY mes DESC;

-- 3. Vista Optimizada de Clientes Activos
CREATE OR REPLACE VIEW vista_clientes_activos_optimizada AS
SELECT 
    c.id_cliente,
    c.nombre,
    m.nombre AS membresia,
    im.fecha_inicio,
    im.fecha_fin,
    (im.fecha_fin - CURRENT_DATE) AS dias_restantes,
    r.nombre AS rutina_asignada
FROM cliente c
JOIN inscripcion_membresia im ON c.id_cliente = im.id_cliente
JOIN membresia m ON im.id_membresia = m.id_membresia
LEFT JOIN rutina r ON c.id_cliente = r.id_cliente
WHERE im.estado = 'Activa'
  AND im.fecha_fin >= CURRENT_DATE;

-- 4. Clientes con Facturación (Combina 2 consultas originales)
SELECT 
    c.nombre,
    COUNT(DISTINCT f.id_factura) AS total_facturas,
    SUM(p.monto) AS total_pagado,
    CASE 
        WHEN COUNT(DISTINCT f.id_factura) > 1 THEN 'Cliente frecuente'
        ELSE 'Cliente ocasional'
    END AS tipo_cliente
FROM cliente c
LEFT JOIN factura f ON c.id_cliente = f.id_cliente
LEFT JOIN pago p ON f.id_factura = p.id_factura
GROUP BY c.id_cliente, c.nombre
HAVING SUM(p.monto) > 0 OR COUNT(DISTINCT f.id_factura) > 0
ORDER BY total_pagado DESC;

-- 5. Procedimiento para Mantenimiento
CREATE OR REPLACE PROCEDURE mantenimiento_automatico()
LANGUAGE plpgsql AS $$
BEGIN
    -- Actualizar estados
    UPDATE inscripcion_membresia
    SET estado = CASE 
        WHEN fecha_fin >= CURRENT_DATE THEN 'Activa'
        ELSE 'Expirada'
    END
    WHERE estado <> 'Cancelada';
    
    -- Eliminar expirados antiguos
    DELETE FROM inscripcion_membresia
    WHERE estado = 'Expirada'
      AND fecha_fin < CURRENT_DATE - INTERVAL '3 years';
    
    RAISE NOTICE 'Mantenimiento completado';
END;
$$;

-- Ejecutar
CALL mantenimiento_automatico();
/*
*/

-- ÍNDICES PARA CONSULTAS FRECUENTES

-- Índices principales (ya creados implícitamente por PRIMARY KEY y UNIQUE)
-- Para búsquedas por cédula (muy frecuente en recepción)
CREATE INDEX idx_cliente_cedula ON cliente(cedula);

-- Para búsquedas por email
CREATE INDEX idx_cliente_email ON cliente(email);

-- Para consultas de membresías activas
CREATE INDEX idx_inscripcion_estado ON inscripcion_membresia(estado);
CREATE INDEX idx_inscripcion_fechas ON inscripcion_membresia(fecha_inicio, fecha_fin);
CREATE INDEX idx_inscripcion_cliente ON inscripcion_membresia(id_cliente);

-- Para consultas de rutinas por cliente
CREATE INDEX idx_rutina_cliente ON rutina(id_cliente);
CREATE INDEX idx_rutina_entrenador ON rutina(id_entrenador);

-- Para ejercicios por grupo muscular (búsquedas frecuentes)
CREATE INDEX idx_ejercicio_grupo ON ejercicio(grupo_muscular);

-- Para pagos y facturas
CREATE INDEX idx_factura_cliente ON factura(id_cliente);
CREATE INDEX idx_factura_fecha ON factura(fecha);
CREATE INDEX idx_pago_factura ON pago(id_factura);
CREATE INDEX idx_pago_fecha ON pago(fecha_pago);

-- Para evaluaciones nutricionales
CREATE INDEX idx_evaluacion_cliente ON evaluacion_nutricional(id_cliente);
CREATE INDEX idx_evaluacion_fecha ON evaluacion_nutricional(fecha);

--EXPLAIN
-- 1. Análisis de Dashboard Clientes
EXPLAIN (ANALYZE, BUFFERS)
SELECT 
    c.nombre,
    im.estado AS estado_membresia,
    im.fecha_inicio,
    im.fecha_fin,
    r.nombre AS rutina,
    e.nombre AS entrenador
FROM cliente c
INNER JOIN inscripcion_membresia im ON c.id_cliente = im.id_cliente
LEFT JOIN rutina r ON c.id_cliente = r.id_cliente
LEFT JOIN entrenador e ON r.id_entrenador = e.id_entrenador
WHERE im.estado = 'Activa'
  AND im.fecha_fin >= CURRENT_DATE;

-- 2. Análisis de Estadísticas
EXPLAIN (ANALYZE, BUFFERS)
SELECT 
    DATE_TRUNC('month', f.fecha) AS mes,
    COUNT(DISTINCT f.id_cliente) AS clientes_activos,
    SUM(p.monto) AS ingresos_totales
FROM factura f
LEFT JOIN pago p ON f.id_factura = p.id_factura
WHERE f.fecha >= CURRENT_DATE - INTERVAL '6 months'
GROUP BY DATE_TRUNC('month', f.fecha);

-- 3. Análisis de Vista Optimizada
EXPLAIN (ANALYZE, BUFFERS)
SELECT * FROM vista_clientes_activos_optimizada
WHERE dias_restantes <= 30;

-- 4. Análisis de Mantenimiento
EXPLAIN (ANALYZE)
UPDATE inscripcion_membresia
SET estado = CASE 
    WHEN fecha_fin >= CURRENT_DATE THEN 'Activa'
    ELSE 'Expirada'
END
WHERE estado <> 'Cancelada';

/*
*/
-- 10. Creación de tablas de auditoría y triggers correspondientes 
-- Tabla de auditoría

CREATE TABLE IF NOT EXISTS auditoria (
    id_auditoria SERIAL PRIMARY KEY,
    tabla_nombre VARCHAR(50),
    operacion VARCHAR(10),
    registro_id INT,
    datos_old JSONB,
    datos_new JSONB,
    usuario TEXT,
    fecha TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Funcion para resumir
CREATE OR REPLACE FUNCTION trigger_auditoria()
RETURNS TRIGGER AS $$
DECLARE
    v_usuario TEXT;
    v_registro_id INT;
BEGIN
    v_usuario := current_user;

    -- Determinar id principal según tabla
    CASE TG_TABLE_NAME
        WHEN 'cliente' THEN v_registro_id := COALESCE(NEW.id_cliente, OLD.id_cliente);
        WHEN 'membresia' THEN v_registro_id := COALESCE(NEW.id_membresia, OLD.id_membresia);
        WHEN 'inscripcion_membresia' THEN v_registro_id := COALESCE(NEW.id_inscripcionM, OLD.id_inscripcionM);
        WHEN 'rutina' THEN v_registro_id := COALESCE(NEW.id_rutina, OLD.id_rutina);
        WHEN 'ejercicio' THEN v_registro_id := COALESCE(NEW.id_ejercicio, OLD.id_ejercicio);
        WHEN 'rutina_ejercicio' THEN v_registro_id := COALESCE(NEW.id_rutina_ejercicio, OLD.id_rutina_ejercicio);
        WHEN 'nutricionista' THEN v_registro_id := COALESCE(NEW.id_nutricionista, OLD.id_nutricionista);
        WHEN 'evaluacion_nutricional' THEN v_registro_id := COALESCE(NEW.id_evaluacion, OLD.id_evaluacion);
        WHEN 'dieta' THEN v_registro_id := COALESCE(NEW.id_dieta, OLD.id_dieta);
        WHEN 'factura' THEN v_registro_id := COALESCE(NEW.id_factura, OLD.id_factura);
        WHEN 'pago' THEN v_registro_id := COALESCE(NEW.id_pago, OLD.id_pago);
        WHEN 'cliente_auth' THEN v_registro_id := COALESCE(NEW.id_auth, OLD.id_auth);
        ELSE v_registro_id := NULL;
    END CASE;

    -- INSERT
    IF TG_OP = 'INSERT' THEN
        INSERT INTO auditoria(tabla_nombre, operacion, registro_id, datos_new, usuario)
        VALUES (TG_TABLE_NAME, 'INSERT', v_registro_id, to_jsonb(NEW), v_usuario);
        RETURN NEW;

    -- UPDATE
    ELSIF TG_OP = 'UPDATE' THEN
        INSERT INTO auditoria(tabla_nombre, operacion, registro_id, datos_old, datos_new, usuario)
        VALUES (TG_TABLE_NAME, 'UPDATE', v_registro_id, to_jsonb(OLD), to_jsonb(NEW), v_usuario);
        RETURN NEW;

    -- DELETE
    ELSIF TG_OP = 'DELETE' THEN
        INSERT INTO auditoria(tabla_nombre, operacion, registro_id, datos_old, usuario)
        VALUES (TG_TABLE_NAME, 'DELETE', v_registro_id, to_jsonb(OLD), v_usuario);
        RETURN OLD;
    END IF;
END;
$$ LANGUAGE plpgsql;

-- Triggers por tabla


-- Cliente
CREATE TRIGGER trg_auditoria_cliente
AFTER INSERT OR UPDATE OR DELETE ON cliente
FOR EACH ROW
EXECUTE FUNCTION trigger_auditoria();

-- Membresía
CREATE TRIGGER trg_auditoria_membresia
AFTER INSERT OR UPDATE OR DELETE ON membresia
FOR EACH ROW
EXECUTE FUNCTION trigger_auditoria();

-- Inscripción Membresía
CREATE TRIGGER trg_auditoria_inscripcion
AFTER INSERT OR UPDATE OR DELETE ON inscripcion_membresia
FOR EACH ROW
EXECUTE FUNCTION trigger_auditoria();

-- Rutina
CREATE TRIGGER trg_auditoria_rutina
AFTER INSERT OR UPDATE OR DELETE ON rutina
FOR EACH ROW
EXECUTE FUNCTION trigger_auditoria();

-- Ejercicio
CREATE TRIGGER trg_auditoria_ejercicio
AFTER INSERT OR UPDATE OR DELETE ON ejercicio
FOR EACH ROW
EXECUTE FUNCTION trigger_auditoria();

-- Rutina_Ejercicio
CREATE TRIGGER trg_auditoria_rutina_ejercicio
AFTER INSERT OR UPDATE OR DELETE ON rutina_ejercicio
FOR EACH ROW
EXECUTE FUNCTION trigger_auditoria();

-- Nutricionista
CREATE TRIGGER trg_auditoria_nutricionista
AFTER INSERT OR UPDATE OR DELETE ON nutricionista
FOR EACH ROW
EXECUTE FUNCTION trigger_auditoria();

-- Evaluación Nutricional
CREATE TRIGGER trg_auditoria_evaluacion
AFTER INSERT OR UPDATE OR DELETE ON evaluacion_nutricional
FOR EACH ROW
EXECUTE FUNCTION trigger_auditoria();

-- Dieta
CREATE TRIGGER trg_auditoria_dieta
AFTER INSERT OR UPDATE OR DELETE ON dieta
FOR EACH ROW
EXECUTE FUNCTION trigger_auditoria();

-- Factura
CREATE TRIGGER trg_auditoria_factura
AFTER INSERT OR UPDATE OR DELETE ON factura
FOR EACH ROW
EXECUTE FUNCTION trigger_auditoria();

-- Pago
CREATE TRIGGER trg_auditoria_pago
AFTER INSERT OR UPDATE OR DELETE ON pago
FOR EACH ROW
EXECUTE FUNCTION trigger_auditoria();

-- Cliente_auth
CREATE TRIGGER trg_auditoria_auth
AFTER INSERT OR UPDATE OR DELETE ON cliente_auth
FOR EACH ROW
EXECUTE FUNCTION trigger_auditoria();



/*AGREGADO PARA EL FRONT*/
-- CORRECCIÓN DE PERMISOS PARA RECEPCIONISTA

-- 1. Dar permisos INSERT y UPDATE a recepcionista en cliente
GRANT INSERT, UPDATE ON cliente TO rol_recepcionista;

-- 2. Dar permisos INSERT en factura y pago
GRANT INSERT ON factura TO rol_recepcionista;
GRANT INSERT ON pago TO rol_recepcionista;

-- 3. Dar permisos en inscripcion_membresia
GRANT INSERT ON inscripcion_membresia TO rol_recepcionista;

-- 4. Dar acceso a secuencias
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO rol_recepcionista;

-- CORRECCIÓN DE VISTAS Y TRIGGERS EN FRONTEND

-- 5. Crear vista para ver índices más detallada
CREATE OR REPLACE VIEW vista_indices_detalle AS
SELECT 
  schemaname,
  tablename,
  indexname,
  indexdef,
  pg_relation_size(indexname::regclass) as tamaño_bytes
FROM pg_indexes 
WHERE schemaname = 'public'
ORDER BY tablename, indexname;

-- 6. Crear vista para triggers más detallada
CREATE OR REPLACE VIEW vista_triggers_detalle AS
SELECT 
  trigger_schema,
  trigger_name,
  event_manipulation,
  event_object_table,
  action_statement,
  action_timing
FROM information_schema.triggers 
WHERE trigger_schema = 'public'
ORDER BY event_object_table, trigger_name;

-- 7. Crear vista para funciones más detallada
CREATE OR REPLACE VIEW vista_funciones_detalle AS
SELECT 
  routine_schema,
  routine_name,
  data_type,
  routine_definition,
  external_language,
  is_deterministic
FROM information_schema.routines 
WHERE routine_schema = 'public'
  AND routine_type = 'FUNCTION'
ORDER BY routine_name;

-- PERMISOS PARA LAS NUEVAS VISTAS

GRANT SELECT ON vista_indices_detalle TO rol_administrador;
GRANT SELECT ON vista_triggers_detalle TO rol_administrador;
GRANT SELECT ON vista_funciones_detalle TO rol_administrador;
GRANT SELECT ON vista_indices_detalle TO rol_recepcionista;
GRANT SELECT ON vista_indices_detalle TO rol_entrenador;
GRANT SELECT ON vista_indices_detalle TO rol_nutricionista;

-- FUNCIÓN PARA REGISTRAR CLIENTE SEGURO

CREATE OR REPLACE FUNCTION registrar_cliente_seguro(
  p_nombre VARCHAR(120),
  p_cedula VARCHAR(20),
  p_telefono VARCHAR(20),
  p_email VARCHAR(150)
) RETURNS INTEGER AS $$
DECLARE
  nuevo_id INTEGER;
BEGIN
  INSERT INTO cliente (nombre, cedula, telefono, email, fecha_registro)
  VALUES (p_nombre, p_cedula, p_telefono, p_email, CURRENT_DATE)
  RETURNING id_cliente INTO nuevo_id;
  
  RETURN nuevo_id;
  
EXCEPTION WHEN OTHERS THEN
  RAISE EXCEPTION 'Error registrando cliente: %', SQLERRM;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Dar permisos para usar la función
GRANT EXECUTE ON FUNCTION registrar_cliente_seguro TO rol_recepcionista;
GRANT EXECUTE ON FUNCTION registrar_cliente_seguro TO rol_administrador;




